### ISSUE TITLE
Not fully working with Safari & Tampermonkey

### ISSUE THREAD

**Issue by JayBrown** [loadletter/ipfs-redirect-userscript#1]
The script is not fully working with Safari (10.1, OS X 10.11.6) & Tampermonkey (latest).

The redirect seems to be working, but Safari intercepts and changes http://localhost:8080 (as it is in the script) to https://localhost:8080. And then Safari says that it can't open the page, because it "can't establish a secure connection to the server 'localhost'". So, Safari is basically shooting itself in the knee. So my question is, if there's a way to use the script to force the browser to redirect to http, and ignore anything related to https?

**Comment by loadletter** [comment]
I don't think there's a way to downgrade to http from javascript

**Comment by JayBrown** [comment]
I just tested it with [ipfs-catcher for Safari](https://github.com/NeoTeo/ipfs-catcher), and this one works, although the functionality isn't great yet, but localhost stays at http. So it seems to be a problem with tampermonkey, because your redirect script doesn't have https. Hmmm…

**Comment by loadletter** [comment]
Well the script was just changing host but not protocol, because I didn't want to soil the minimalism of that solution, now I've replaced it with the code from that safari extension and it seems to work.

**Comment by JayBrown** [comment]
However, by just using the Safari extension code, it's now breaking path elements after the parent hash, and multiple hashes in one URL, e.g. `https://ipfs.io/ipfs/QmNZiPk974vDsPmQii3YbrMKfi12KTSNM7XMiYyiea4VYZ/example#/ipfs/QmRFTtbyEp3UaT67ByYW299Suw7HKKnWK6NJMdNFzDjYdX/config/readme.md`

**Comment by loadletter** [comment]
I'll take a look when I have some time, but I haven't played with ipfs in a while

**Comment by JayBrown** [comment]
I might have found a solution. The problem of the original Safari extension script was that it was looking for `?(Qm\w{44})/`, i.e. "Qm" plus 44 instances of a word character "\w". However, a complex IPFS address can (a) be longer, and (b) have a slash etc., i.e. non-word characters, so it would be better to look for `?(Qm.+)`, i.e. "Qm" plus any number "+" (except zero) of any character "." (excludes newline and line-terminator). Seems to work on my system. Feel free to incorporate it. (Changed the variable names.)

```
var theURL = window.location.toString();

var regExp = /.?(\/ipfs\/|\/ipns\/)?(Qm.+)/;
var exclDom = /http:\/\/localhost.*/;
var matchURL = regExp.exec(theURL);

if (matchURL !== null) {

    console.log(matchURL);
    if (matchURL.length > 1 && !exclDom.test(theURL)) {

        // IPFS protocol
        var theProtocol = matchURL[1];
        ipProtocol = (theProtocol === null) ? "/ipfs/" : theProtocol;

        // IPFS hash
        var ipHash = matchURL[2];
        if( ipHash !== null ) {
            ipProtocol += ipHash;
            var newURL = "http://localhost:8080"+ipProtocol;
            window.location = newURL;
        }
    }
}
```

**Comment by loadletter** [comment]
Thanks for looking into it, do you think the greasemonkey header should be changed to run the script on any page (or maybe those containing */ipfs/* & ipns) since it currently only runs on ipfs.io?

**Comment by JayBrown** [comment]
Definitely. There are already a couple of public gateways besides ipfs.io. (Though I don't know which anymore; stumbled across a list a few weeks ago.) But as soon as IPFS takes off, there will be more and more. So the `@match` should be a bit more general, e.g.

```
// @match        *://*/ipfs/*
// @match        *://*/ipns/*
```

**Comment by loadletter** [comment]
Done
